### ISSUE TITLE
Partitions of "config" and "cache" failed to be created 

### ISSUE THREAD

**Issue by soramame21** [ARMmbed/meta-mbed-raspberrypi#4]
I built Mbed Edge on Yocto image with this mete-mbed-raspberrypi layer without error.
the Mbed Edge on Raspberry Pi3 can connect to Mbed Cloud without errors, but partitions of **config** and **cache** are missing.
I'm working on a linux PC (Ubuntu 16.04) to build the **rpi-mbed-image-raspberrypi3-2018xxx.rootfs.rpi-sdimg**.
According to analysis, I assume following command lines in /classes/mbed_sdcard_image-rpi.bbclass are not executed effectively.
```
	#create empty CONFIG partition
	dd if=/dev/zero of=${IMGDEPLOYDIR}/config.ext3 seek=${CONFIG_SIZE} count=0 bs=1k
	mkfs.ext3 -L config -F $extra_imagecmd ${IMGDEPLOYDIR}/config.ext3
	dd if=${IMGDEPLOYDIR}/config.ext3 of=${SDIMG} conv=notrunc seek=1 bs=$(expr 1024 \* ${CONFIGSTART}) && sync && sync

	#create empty CACHE partition
	dd if=/dev/zero of=${IMGDEPLOYDIR}/cache.ext3 seek=$(expr ${SDIMG_SIZE} \- ${CACHESTART}) count=0 bs=1k
	mkfs.ext3 -L "cache" -F $extra_imagecmd ${IMGDEPLOYDIR}/cache.ext3
	dd if=${IMGDEPLOYDIR}/cache.ext3 of=${SDIMG} conv=notrunc seek=1 bs=$(expr 1024 \* ${CACHESTART}) && sync && sync
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTGW-582

**Comment by jjaakola-arm** [comment]
We will investigate this issue.

**Comment by soramame21** [comment]
@jjaakola-arm, @ciarmcom Thanks for your support. I cleaned all derived files and rebuilt it, then the **config** and **cache** partitions are created!!
